---

- hosts: local
  gather_facts: false
  roles:
    - scanner
    - devtools
  tags:
    - local

- hosts: raspi
  remote_user: pi
  roles:
    - pi16adc
  tags:
    - pi16adc
    - raspi

- hosts: raspi
  remote_user: pi
  roles:
    - moisturemon
  tags:
    - monitor
    - raspi
    - check

- hosts: raspi
  remote_user: pi
  roles:
    - copydata
  tags:
    - copy
    - check

- hosts: local
  gather_facts: false
  tasks:
  - name:
    shell: python ./update_data.py && rm ./temp_data.csv
    args:
      chdir: '{{ playbook_dir }}'
  tags:
    - copy
    - check

