---
- name: install packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - vim
    - git
    - python-pip
    - python-tk
    - sshpass

- name: install pip packages
  pip:
    name: matplotlib
    state: present
